name: "Seafile"
description: "Run Seafile in home assistant!"
image: mnlphlp/ha_seafile
version: "1.0.3"
slug: "seafile"
arch:
  - aarch64
  - amd64
webui: http://[HOST]:[PORT:80]
ports: 
  '80/tcp': 8080
ports_description: 
  '80/tcp': 'seafile ui'
services:
  - mysql:need
options:
  db: core-mariadb
  db_user: seafile
  db_pass: seafile
  tz: Europe/Berlin
  admin_email: sea@file.com
  admin_pass: seafile
  server_hostname: hassio.local
schema:
  db: str
  db_user: str
  db_pass: str
  tz: str
  admin_email: str
  admin_pass: str
  server_hostname: str
