name: "Pydio Cells Home"
description: "Run Pydio Cells Home as addon in home assistant!"
image: mnlphlp/ha-cells
version: "0.1.3"
slug: "cells"
arch:
  - aarch64
  - amd64
webui: https://[HOST]:[PORT:80]
ports:
  "80/tcp": 8080
ports_description:
  "80/tcp": "cells ui"
services:
  - mysql:need
options:
  db: core-mariadb
  db_user: cells
  db_pass: cells
  server_hostname: hassio.local
  no_tls: 1
schema:
  db: str
  db_user: str
  db_pass: str
  server_hostname: str
  no_tls: bool
